### ISSUE TITLE
Wird dieser Adapter noch weiter entwickelt

### ISSUE THREAD

**Issue by tomg1970** [foxthefox/ioBroker.nest#11]
Hallo wird dieser Adapter noch weiterentwickelt. Das wäre echt super 
wenn man die Nest Hello (Türstation) einbinden könnte.

**Comment by foxthefox** [comment]
Dem Adapter wurde die Lebensgrundlage entzogen.
Vor geraumer Zeit wurde der notwendige Entwicklerzugang geschlossen. D.h. jeder der den Adapter benutzen wollte, brauchte diesen Zugang und konnte somit die API benutzen. Wer noch einen alten Zugang hat, da geht es wohl noch, ansonsten ist es halt vorbei. Selbst die ursprüngliche Funktion des Energiesparens mit dem Netzbetreiber in USA ist durch dieses Umschwenken weggefallen. Google hat halt so seine eigenen Geschäftspraktiken.

Ich fand das Thermostat ganz interessant, hab es nie benutzt, weil die API recht gut strukturiert war und ein anderer Biobroker user Bedarf meldete, hatte ich mich kurz der Challenge gestellt.

**Comment by tomg1970** [comment]
Vielen lieben Dank für Deine Rückmeldung.
Das ist sehr schade, dass deine schon verwendete Zeit nutzlos ist.
Und genauso schade ist es, dass man jetzt zB meine Nest Hello Türstation nicht Visualisieren kann (IoBroker)

**Comment by Maj0rT** [comment]
Seit etwa 2 Monaten gibt es doch die neue Entwickler-Api direkt von Google für Nest. Darüber müsste das doch nun wieder möglich sein?
https://developers.google.com/nest/device-access

**Comment by foxthefox** [comment]
wusste ich nicht, evtl. ists ja wieder unter Beibehaltung der API auferstanden.
Muss ich mir bei Gelegenheit mal anschauen.

**Comment by tomg1970** [comment]
Hallo, hab gesehen, dass du ganz in der Nähe wohnst. Echt cool.
Schau mal hier hab ich auch was gefunden:

[https://developers.google.com/nest/device-access/api/doorbell]
[ https://www.home-assistant.io/integrations/nest/](url)

**Comment by foxthefox** [comment]
schade ist, daß der smokedetector nicht dabei ist. wegen dessen gab es auch diverse Anfragen damals.
Wenn man sich das Procedere um einen login einzurichten anschaut, ist es ja scheinbar noch aufwendiger als vorher bei NEST. naja evtl. muß ich im iobroker forum einen poll machen, ob denn jeder Anwender auch bereit ist 5$ zu investieren.
damals hatte ich auch etwas mehr zeit und Laune mal kurz diese Herausforderung anzunehmen

**Comment by DerDom** [comment]
Ich wäre mit €5 dabei. Gerne auch mehr!

**Comment by cracyfloyd** [comment]
Hat sich schon jemand mit Kenntnissen gefunden der diesen Adapter weiter entwickelt um z.B die neuere Doorbell mit Akku in IOBroker zu nutzen??????
Würde mich sehr freuen.....

**Comment by foxthefox** [comment]
habs mir noch nicht weiter angeschaut, der fritzdect Adapter braucht noch ein wenig updates, dann noch jeelink und dann evtl. hier

**Comment by foxthefox** [comment]
habe mit dem Umbau begonnen

**Comment by Freaky-BoyHP** [comment]
Ich würde gern auf die neuen Kameras über den Nest adapter zugreifen. Besonders interessiert mich aktivierung/Deaktivierung und video-stream bzw. Ein Bild abzurufen.
Den Zugang für die 5$ habe ich schon gekauft. Allerdings hat dann doch meine Kenntnis nicht ausgereicht um mit der API klarzukommen.

Wie sieht der aktuelle Stand aus? Falls du eine Testumgebung brauchst, kannst du dich gern melden.

**Comment by foxthefox** [comment]
danke für das Angebot, habe derzeitig noch nicht den freien Kopf für den Adapter. Die dunklen Tage kommen

**Comment by ckoeber83** [comment]
Hi,

ich habe NEST-Protect und wäre auch an einer nativen Integration in ioBroker interessiert.

Aktuell nutze ich das [Nest plug-in](https://github.com/chrisjshull/homebridge-nest) for [Homebridge](https://github.com/nfarina/homebridge)

Als Zugang nutzte ich die [Google Account Methode](https://github.com/chrisjshull/homebridge-nest#using-a-google-account).
Darüber konnte ich mal Ende letzten Jahres alle mein Protects einlesen, aber die haben sich nie aktualisiert 🤔: (_Alle Werte auf null_)

![grafik](https://user-images.githubusercontent.com/52466072/201502096-77558442-c363-4a1e-b1ef-bcb613a1d034.png)

Ich habe dazu die refresh token Methode genutzt, welcher aber jetzt seit Oktober 2022 seitens Google nicht mehr gehen soll:

_(Note: the plug-in used to support two ways to authenticate with Google, the refresh token method and the cookies method. The refresh token method no longer works due to Google-side changes in October 2022, so now we only document the cookies method._
Sektion "refresh Token" wurde daraufhin aus [homebridge-nest readme](https://github.com/chrisjshull/homebridge-nest/commit/999faba0407c4560c31f6c1e04756138c596daa9) enfernt.

![grafik](https://user-images.githubusercontent.com/52466072/201502606-9a485906-0bf8-41a0-885c-f4bf453bc28a.png)

Bleibt also nur noch die [hier](https://github.com/chrisjshull/homebridge-nest#using-a-google-account) beschrieben Cookies Methode. Habe ich aber noch nicht getestet und mache ich vielleicht demnächst mal...
Aber kann mir nicht vorstellen, das dies so gut läuft. Cookies können auslaufen und müssen dann immer erneuert werden. 🤔

**Comment by foxthefox** [comment]
Ich werde demnächst etwas Zeit haben mich intensiver mit nest und google zu beschäftigen.
Welche Arten von Zugang es alles gibt, muß ich mir mal anschauen. 
Ich hoffe das die API gut dokumentiert ist und sich für die bestehenden Geräte nicht ändert.

**Comment by foxthefox** [comment]
Für mich sieht es so aus, daß ich die SDM API von google zu benutzen habe. Damit gibt es derzeitig (und das schon seit langem) keine Unterstützung von Nest Protect. Keine Ahnung warum hier die Geräte nicht migriert werden.
